site_name: I2P-Bote Protocol
site_url: https://bote.readthedocs.io
site_description: I2P-Bote Protocol
site_author: polistern

repo_url: https://github.com/PurpleBote/bote
repo_name: PurpleBote/bote

nav:
- Home: index.md
- Glossary of Terms: terms.md
- Version 5 (current):
  - Description: v5/index.md
  - Introduction: v5/introduction.md
  - Kademlia: v5/kademlia.md
  - Packet Types: v5/packet_types.md
  - Protocols: v5/protocols.md
  - Cryptography: v5/cryptography.md
- Version 6 (draft):
  - Description: v6/index.md
  - Introduction: v6/introduction.md
  - Kademlia: v6/kademlia.md
  - Packet Types: v6/packet_types.md
  - Protocols: v6/protocols.md
  - Cryptography: v6/cryptography.md
- Deprecated:
  - Version 4:
    - Description: old/v4/index.md
    - Information: old/v4/info.md
  - Version 3:
    - Description: old/v3/index.md
    - Information: old/v3/info.md
  - Version 2:
    - Description: old/v2/index.md
    - Information: old/v2/info.md
  - Version 1:
    - Description: old/v1/index.md
    - Information: old/v1/info.md

copyright: <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a>, Maintained by <a href="https://github.com/polistern">polistern</a>

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - git-revision-date
  - i18n:
      default_language: en
      docs_structure: suffix
      languages:
        en:
          name: English
          build: true
          site_name: I2P-Bote Protocol
        ru:
          name: Russian
          build: true
          site_name: Протокол I2P-Bote
      nav_translations:
        ru:
          Home: Главная
          Glossary of Terms: Словарь терминов
          Version 5 (current): Версия 5 (текущая)
          Description: Описание
          Introduction: Введение
          Packet Types: Типы пакетов
          Protocols: Протоколы
          Cryptography: Криптография
          Version 6 (draft): Версия 6 (черновик)
          Deprecated: Устаревшие
          Version 4: Версия 4
          Version 3: Версия 3
          Version 2: Версия 2
          Version 1: Версия 1
          Information: Информация

theme:
  name: material
  palette:
    scheme: slate
    primary: purple
  custom_dir: overrides/
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
